name: leafguard
description: LeafGuard Admin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  table_calendar: ^3.0.9
  google_fonts: ^4.0.3
  provider: ^6.0.5
  intl: ^0.18.0
  url_strategy: ^0.2.0
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  fluttertoast: 8.0.8
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  universal_html: ^2.2.1
  openid_client: ^0.4.7
  simple_animations: ^3.1.1
  flutter_secure_storage: ^8.0.0
  file_picker: ^5.2.11
  country_picker: ^2.0.19
  dropdown_button2: ^2.1.3
  number_inc_dec: ^0.8.0
  intl_phone_field: ^3.1.0
  flutter_svg: ^1.1.6
  pdf: ^3.6.0
  path_provider: ^2.0.3
  multi_select_flutter: ^4.1.3
  awesome_snackbar_content: any
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  analyzer: any

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/logo.PNG
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
